### ISSUE TITLE
You are missing the KEY

### ISSUE THREAD

**Issue by SupervisionT** [snocks/Emotion-API#4]
Dear,
I faced the following issue, where when I clicked on the button nothing happened and there is error in the key as shown in the console.

![image](https://cloud.githubusercontent.com/assets/23292204/23015381/6c123dd0-f3e7-11e6-82d8-e3819dfd9513.png)

**Comment by muhmushtaha** [comment]
I think this error because we hide the API keys.
to make it run I think you want to download the project and put your API keys
