### ISSUE TITLE
File modularisation

### ISSUE THREAD

**Issue by besarthoxhaj** [snocks/Emotion-API#5]
I think you can move some code outside of `javascript.js`.

A good example would be the images array -> https://github.com/snocks/Emotion-API/blob/master/javascript.js#L1

```html
<!DOCTYPE html>
<html>
  <body>
    <!-- ... -->
    <script type="text/javascript" src="images_store.js"></script>
    <!-- ... -->
  </body>
</html>
```

**Comment by muhmushtaha** [comment]
We add it
